#!/bin/bash

# Parameter 1: Current directory for test oi session
# 
# To have the test editor launched respond with "initialized|editor"
# rather than just "initialized"
#
# The following protocol goes for communicating between this test
# and the test runner when printed to std out.
#
#	- passed
#		Markes the test run as completed for this test and marks it
#		as passed.
#	- failed
#		Markes the test run as completed for this test and marks it
#		as failed. Can pass optional error description separated by |
#	- command|[OI COMMAND]
#		Runs the specified oi command in the test environment. The 
#		output and events generated by the command can be verified
#		through the commands below.
#	- hasoutput|[TEXT TO MATCH TO LINE]
#		Matches output lines generated by the test against line 
#		submitted with the command.
#	- hasevent|[TEXT TO MATCH TO LINE]
#		Matches event lines generated by the test against line
#		submitted with the command.

ROOT=`dirname $0`

echo "initialized"
while IFS='|' read -ra COMMAND; do
	# The test script is told to exit
	if [ "${COMMAND[0]}" == "shutdown" ] ; then
		break
	fi

	# Write one line pr test
	if [ "${COMMAND[0]}" == "get-tests" ] ; then
		echo "When given a passing test it should output passed"
		echo "When given a failing test it should output failed"
		echo "When given a inconclusive test it should output question marks"
	fi

	# Handling test runs
	if [ "${COMMAND[0]}" == "test" ] ; then
		case "${COMMAND[1]}" in
			"When given a passing test it should output passed")
				echo "command|pkgtest $ROOT/pkgtest.passing.test.sh"
				echo "hasoutput|PASSED A passing test"
				IFS='|' read -ra VALUE
				if [ "${VALUE}" != "true" ] ; then
					echo "failed"
				else
					echo "passed"
				fi
				;;
			"When given a failing test it should output failed")
				echo "command|pkgtest $ROOT/pkgtest.failed.test.sh"
				echo "hasoutput|FAILED A failing test"
				IFS='|' read -ra VALUE
				if [ "${VALUE}" != "true" ] ; then
					echo "failed"
				else
					echo "passed"
				fi
				;;
			"When given a inconclusive test it should output question marks")
				echo "command|pkgtest $ROOT/pkgtest.inconclusive.test.sh"
				echo "hasoutput|?????? A inconclusive test"
				IFS='|' read -ra VALUE
				if [ "${VALUE}" != "true" ] ; then
					echo "failed"
				else
					echo "passed"
				fi
				;;
		esac
	fi

	echo "end-of-conversation"
done