#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [ "$1" == "initialize" ]; then
{
	mono $SCRIPT_DIR/C#-plugin/C#.exe "$@" &
	sleep 0.5
}
else
{
	echo mono $SCRIPT_DIR/C#-plugin/C#.exe send "$@"
	mono $SCRIPT_DIR/C#-plugin/C#.exe send "$@"
}
fi